### ISSUE TITLE
IDs lost for marker genes due to `row.names = FALSE`

### ISSUE THREAD

**Issue by PeteHaitch** [MarioniLab/simpleSingleCell#2]
Hey Aaron,

You might want to switch `row.names = TRUE` in `write.table()` for the examples like that in https://bioconductor.org/packages/devel/workflows/vignettes/simpleSingleCell/inst/doc/work-1-reads.html#112_detecting_marker_genes_between_clusters, otherwise the resulting table doesn't contain any gene IDs.

Cheers,
Pete

**Comment by LTLA** [comment]
Thanks, probably a leftover from the time where there was an explicit column for the gene name.
