### ISSUE TITLE
Inconsistent use of blocking?

### ISSUE THREAD

**Issue by PeteHaitch** [MarioniLab/simpleSingleCell#3]
Here, you block in `trendVar()` but not in `decomposeVar()`. Does this matter?

https://github.com/MarioniLab/simpleSingleCell/blob/d4c6d8dbf1e2b751bc5b53f1d62155c405f00da2/vignettes/work-5-mnn.Rmd#L164-L165

**Comment by LTLA** [comment]
`decomposeVar` should use the blocking information in `trendVar`'s output, see `?decomposeVar`.

**Comment by PeteHaitch** [comment]
Now I see it. Thanks.
