### ISSUE TITLE
Biocpkg's 'vignette'  argument deprecated?

### ISSUE THREAD

**Issue by AJABADI** [MarioniLab/simpleSingleCell#4]
Hi Aaron,
Great work!

I tried to reproduced some of the Rmarkdown files and when I try to run this:

`BiocStyle::Biocpkg("simpleSingleCell", vignette="xtra-1-qc.html#assumptions-of-outlier-identification", label="this section")`

 I get the following error:

> Error in BiocStyle::Biocpkg("simpleSingleCell", vignette = "xtra-1-qc.html#assumptions-of-outlier-identification",  : 
>   unused arguments (vignette = "xtra-1-qc.html#assumptions-of-outlier-identification", label = "this section")

I was wondering if that's because the Biocpkg function has deprecated the arguments, and if so, is there an alternative way to do it?

Cheers

R version 3.5.0 (2018-04-23)
Using Bioconductor 3.7 (BiocInstaller 1.30.0), R 3.5.0 (2018-04-23).
> packageVersion("BiocStyle")
[1] ‘2.8.2’

**Comment by LTLA** [comment]
You need the development version of BiocStyle (and of all Bioconductor packages, actually). Run:

```r
BiocManager::install(version="3.8")
```
