### ISSUE TITLE
Run into error when testing the tutorial

### ISSUE THREAD

**Issue by italycq** [MarioniLab/simpleSingleCell#7]
Hi, 
I am testing the code on the tutorial at the URL below:
https://bioconductor.org/packages/3.9/workflows/vignettes/simpleSingleCell/inst/doc/batch.html#7_using_the_corrected_values_in_downstream_analyses

I run into issue in the following section (section 2.2.1), although anything prior to that point can be run through:
>muraro.fname <- bfcrpath(bfc, file.path("ftp://ftp.ncbi.nlm.nih.gov/geo/series",
    "GSE85nnn/GSE85241/suppl",
    "GSE85241%5Fcellsystems%5Fdataset%5F4donors%5Fupdated%2Ecsv%2Egz"))
> Error in connection_connect(dbname, loadable.extensions, flags, vfs) :
>   Could not connect to database:
> unable to open database file
> 

any ideas what is the problem here?
Thanks and best
MY

**Comment by LTLA** [comment]
From what you're saying, the prior `bfcrpath` call (to create `grun.fname`) worked fine. If it's just `muraro.fname` that's not working, I would be quite confused. The only possibility would be that _BiocFileCache_ or its dependencies do not like the character symbols in the GEO URL; but this shouldn't be the case if you're using the latest versions of all packages. Make sure you're using the latest version of _BiocFileCache_ (1.6.0).

Note that it is customary to show your session information in your original post.

**Comment by italycq** [comment]
Hi, LTLA:

Thx for the advice. I did check my sessionInfo() as below, which indeed has BiocFileCache_1.7.0 higher than what you suggested 1.6.0, could this be problem?
> sessionInfo()
R Under development (unstable) (2019-02-05 r76063)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /opt/nasapps/development/R/3.6.0/lib/R/lib/libRblas.so
LAPACK: /opt/nasapps/development/R/3.6.0/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] scran_1.11.20               scater_1.11.10
 [3] ggplot2_3.1.0               SingleCellExperiment_1.5.2
 [5] SummarizedExperiment_1.13.0 DelayedArray_0.9.8
 [7] BiocParallel_1.17.9         matrixStats_0.54.0
 [9] GenomicRanges_1.35.1        GenomeInfoDb_1.19.1
[11] org.Hs.eg.db_3.7.0          AnnotationDbi_1.45.0
[13] IRanges_2.17.4              S4Vectors_0.21.10
[15] Biobase_2.43.1              BiocGenerics_0.29.1
[17] bindrcpp_0.2.2              BiocFileCache_1.7.0
[19] dbplyr_1.3.0

what do you think?
Thx
MY

**Comment by LTLA** [comment]
No, the version numbers are fine if you're using R-devel. This means that you're using Bioc-devel, which should be fine if you're `BiocManager::valid()` and all packages are up-to-date with `BiocManager::install()`.

To be absolutely clear: you are trying to run:

```r
library(BiocFileCache)
bfc <- BiocFileCache("raw_data", ask = FALSE)
muraro.fname <- bfcrpath(bfc, file.path("ftp://ftp.ncbi.nlm.nih.gov/geo/series",
    "GSE85nnn/GSE85241/suppl",
    "GSE85241%5Fcellsystems%5Fdataset%5F4donors%5Fupdated%2Ecsv%2Egz"))
```

The same code has no problems running on my computer. I conclude there is something wrong with your system, e.g., you don't have enough disk space, or you don't have permissions to write to `raw_data`.

I also find it bemusing that you were able to run the corresponding code for `grun.fname`. I don't know how the file system could change between the processing of one data set to the other.

**Comment by italycq** [comment]
Thx for the info. Turns out, if I re-run the commands from the start up to the command muraro.fname <- bfcrpath(bfc, file.path,...), I will run into the same issues that I reported before. Only if I run the following command again (which has been run earlier in the tutorial) as in your last comment:
bfc <- BiocFileCache("raw_data", ask = FALSE)
the muraro.fname <- bfcrpath(bfc, file.path,...) would work.

So maybe in the tutorial, the bfc <- BiocFileCache("raw_data", ask = FALSE) shall be added before we run
the muraro.fname <- bfcrpath(bfc, file.path,...)  on section 2.2.1.

Thx and best
MY

**Comment by LTLA** [comment]
I think this may be a problem specific to your set-up. I (and the BioC build system, and many other people) have no problems with compiling the vignette as it is currently written. I hope you are not deleting or modifying the `raw_data` directory in between the two calls, or changing your working directory, etc.
